import { MdAdminPanelSettings, MdDashboard, MdReceipt, MdAnalytics,MdInventory } from 'react-icons/md';
import { FaBoxes, FaIndustry, FaShoppingCart, FaDollarSign, FaServicestack, FaUserFriends } from 'react-icons/fa';

export const sidebarIcons=[
    {name:"Admin",icon:MdAdminPanelSettings},
    {name:"Core",icon:MdDashboard },
    {name:"Procurement",icon:MdReceipt},
    {name:"Inventory",icon:FaBoxes },
    {name:"Manufacture",icon:FaIndustry},
    {name:"Sales",icon:FaShoppingCart},
    {name:"Finance",icon:FaDollarSign},
    {name:"Assets",icon:MdInventory},
    {name:"Services",icon:FaServicestack},
    {name:"CRM",icon:FaUserFriends},
    {name:"Analytics",icon:MdAnalytics},
 
];

export const tableData=[
  {
    firstName:"John",
    lastName:"Doe",
    address:"123 Elm street",
    mobile:"555-1234",
    email:"John.doe@example.com",
    department:"Sales",
    designation:"Manager",
    updatedIcon:"J",
    updatedDate:"2024-05-08",
    updatedTime:"1:45PM",
    number:1
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    address: "456 Oak Avenue",
    mobile: "555-5678",
    email: "jane.smith@example.com",
    department: "Marketing",
    designation: "Director",
    updatedIcon: "S",
    updatedDate: "2024-03-08",
    updatedTime: "2:10PM",
    number: 2
  },
  {
    firstName: "Alice",
    lastName: "Johnson",
    address: "789 Pine Road",
    mobile: "555-8765",
    email: "alice.johnson@example.com",
    department: "HR",
    designation: "Coordinator",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "2:30PM",
    number: 3
  },
  {
    firstName: "Bob",
    lastName: "Brown",
    address: "321 Maple Lane",
    mobile: "555-2345",
    email: "bob.brown@example.com",
    department: "IT",
    designation: "Technician",
    updatedIcon: "B",
    updatedDate: "2024-03-08",
    updatedTime: "3:00PM",
    number: 4
  },
  {
    firstName: "Charlie",
    lastName: "Davis",
    address: "654 Birch Boulevard",
    mobile: "555-3456",
    email: "charlie.davis@example.com",
    department: "Finance",
    designation: "Analyst",
    updatedIcon: "B",
    updatedDate: "2024-03-08",
    updatedTime: "3:15PM",
    number: 5
  },
  {
    firstName: "Eve",
    lastName: "Miller",
    address: "987 Cedar Street",
    mobile: "555-4567",
    email: "eve.miller@example.com",
    department: "Operations",
    designation: "Supervisor",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "3:30PM",
    number: 6
  },
  {
    firstName: "Frank",
    lastName: "Wilson",
    address: "321 Spruce Way",
    mobile: "555-5678",
    email: "frank.wilson@example.com",
    department: "Legal",
    designation: "Consultant",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "3:45PM",
    number: 7
  },
  {
    firstName: "Grace",
    lastName: "Lee",
    address: "654 Palm Drive",
    mobile: "555-6789",
    email: "grace.lee@example.com",
    department: "Engineering",
    designation: "Developer",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "4:00PM",
    number: 8
  },
  {
    firstName: "Henry",
    lastName: "Taylor",
    address: "987 Fir Street",
    mobile: "555-7890",
    email: "henry.taylor@example.com",
    department: "R&D",
    designation: "Scientist",
    updatedIcon: "A",
    updatedDate: "2024-03-08",
    updatedTime: "4:15PM",
    number: 9
  },
  {
    firstName: "Isabel",
    lastName: "Anderson",
    address: "123 Aspen Court",
    mobile: "555-8901",
    email: "isabel.anderson@example.com",
    department: "Customer Support",
    designation: "Agent",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "4:30PM",
    number: 10
  },
  {
    firstName: "Jack",
    lastName: "Thomas",
    address: "456 Cypress Avenue",
    mobile: "555-9012",
    email: "jack.thomas@example.com",
    department: "Quality Assurance",
    designation: "Inspector",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "4:45PM",
    number: 11
  },
  {
    firstName: "Karen",
    lastName: "Jackson",
    address: "789 Redwood Road",
    mobile: "555-0123",
    email: "karen.jackson@example.com",
    department: "Logistics",
    designation: "Coordinator",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "5:00PM",
    number: 12
  },
  {
    firstName:"John",
    lastName:"Doe",
    address:"123 Elm street",
    mobile:"555-1234",
    email:"John.doe@example.com",
    department:"Sales",
    designation:"Manager",
    updatedIcon:"J",
    updatedDate:"2024-05-08",
    updatedTime:"1:45PM",
    number:1
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    address: "456 Oak Avenue",
    mobile: "555-5678",
    email: "jane.smith@example.com",
    department: "Marketing",
    designation: "Director",
    updatedIcon: "S",
    updatedDate: "2024-03-08",
    updatedTime: "2:10PM",
    number: 2
  },
  {
    firstName: "Alice",
    lastName: "Johnson",
    address: "789 Pine Road",
    mobile: "555-8765",
    email: "alice.johnson@example.com",
    department: "HR",
    designation: "Coordinator",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "2:30PM",
    number: 3
  },
  {
    firstName: "Bob",
    lastName: "Brown",
    address: "321 Maple Lane",
    mobile: "555-2345",
    email: "bob.brown@example.com",
    department: "IT",
    designation: "Technician",
    updatedIcon: "B",
    updatedDate: "2024-03-08",
    updatedTime: "3:00PM",
    number: 4
  },
  {
    firstName: "Charlie",
    lastName: "Davis",
    address: "654 Birch Boulevard",
    mobile: "555-3456",
    email: "charlie.davis@example.com",
    department: "Finance",
    designation: "Analyst",
    updatedIcon: "B",
    updatedDate: "2024-03-08",
    updatedTime: "3:15PM",
    number: 5
  },
  {
    firstName: "Eve",
    lastName: "Miller",
    address: "987 Cedar Street",
    mobile: "555-4567",
    email: "eve.miller@example.com",
    department: "Operations",
    designation: "Supervisor",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "3:30PM",
    number: 6
  },
  {
    firstName: "Frank",
    lastName: "Wilson",
    address: "321 Spruce Way",
    mobile: "555-5678",
    email: "frank.wilson@example.com",
    department: "Legal",
    designation: "Consultant",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "3:45PM",
    number: 7
  },
  {
    firstName: "Grace",
    lastName: "Lee",
    address: "654 Palm Drive",
    mobile: "555-6789",
    email: "grace.lee@example.com",
    department: "Engineering",
    designation: "Developer",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "4:00PM",
    number: 8
  },
  {
    firstName: "Henry",
    lastName: "Taylor",
    address: "987 Fir Street",
    mobile: "555-7890",
    email: "henry.taylor@example.com",
    department: "R&D",
    designation: "Scientist",
    updatedIcon: "A",
    updatedDate: "2024-03-08",
    updatedTime: "4:15PM",
    number: 9
  },
  {
    firstName: "Isabel",
    lastName: "Anderson",
    address: "123 Aspen Court",
    mobile: "555-8901",
    email: "isabel.anderson@example.com",
    department: "Customer Support",
    designation: "Agent",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "4:30PM",
    number: 10
  },
  {
    firstName: "Jack",
    lastName: "Thomas",
    address: "456 Cypress Avenue",
    mobile: "555-9012",
    email: "jack.thomas@example.com",
    department: "Quality Assurance",
    designation: "Inspector",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "4:45PM",
    number: 11
  },
  {
    firstName: "Karen",
    lastName: "Jackson",
    address: "789 Redwood Road",
    mobile: "555-0123",
    email: "karen.jackson@example.com",
    department: "Logistics",
    designation: "Coordinator",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "5:00PM",
    number: 12
  },
  {
    firstName:"John",
    lastName:"Doe",
    address:"123 Elm street",
    mobile:"555-1234",
    email:"John.doe@example.com",
    department:"Sales",
    designation:"Manager",
    updatedIcon:"J",
    updatedDate:"2024-05-08",
    updatedTime:"1:45PM",
    number:1
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    address: "456 Oak Avenue",
    mobile: "555-5678",
    email: "jane.smith@example.com",
    department: "Marketing",
    designation: "Director",
    updatedIcon: "S",
    updatedDate: "2024-03-08",
    updatedTime: "2:10PM",
    number: 2
  },
  {
    firstName: "Alice",
    lastName: "Johnson",
    address: "789 Pine Road",
    mobile: "555-8765",
    email: "alice.johnson@example.com",
    department: "HR",
    designation: "Coordinator",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "2:30PM",
    number: 3
  },
  {
    firstName: "Bob",
    lastName: "Brown",
    address: "321 Maple Lane",
    mobile: "555-2345",
    email: "bob.brown@example.com",
    department: "IT",
    designation: "Technician",
    updatedIcon: "B",
    updatedDate: "2024-03-08",
    updatedTime: "3:00PM",
    number: 4
  },
  {
    firstName: "Charlie",
    lastName: "Davis",
    address: "654 Birch Boulevard",
    mobile: "555-3456",
    email: "charlie.davis@example.com",
    department: "Finance",
    designation: "Analyst",
    updatedIcon: "B",
    updatedDate: "2024-03-08",
    updatedTime: "3:15PM",
    number: 5
  },
  {
    firstName: "Eve",
    lastName: "Miller",
    address: "987 Cedar Street",
    mobile: "555-4567",
    email: "eve.miller@example.com",
    department: "Operations",
    designation: "Supervisor",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "3:30PM",
    number: 6
  },
  {
    firstName: "Frank",
    lastName: "Wilson",
    address: "321 Spruce Way",
    mobile: "555-5678",
    email: "frank.wilson@example.com",
    department: "Legal",
    designation: "Consultant",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "3:45PM",
    number: 7
  },
  {
    firstName: "Grace",
    lastName: "Lee",
    address: "654 Palm Drive",
    mobile: "555-6789",
    email: "grace.lee@example.com",
    department: "Engineering",
    designation: "Developer",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "4:00PM",
    number: 8
  },
  {
    firstName: "Henry",
    lastName: "Taylor",
    address: "987 Fir Street",
    mobile: "555-7890",
    email: "henry.taylor@example.com",
    department: "R&D",
    designation: "Scientist",
    updatedIcon: "A",
    updatedDate: "2024-03-08",
    updatedTime: "4:15PM",
    number: 9
  },
  {
    firstName: "Isabel",
    lastName: "Anderson",
    address: "123 Aspen Court",
    mobile: "555-8901",
    email: "isabel.anderson@example.com",
    department: "Customer Support",
    designation: "Agent",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "4:30PM",
    number: 10
  },
  {
    firstName: "Jack",
    lastName: "Thomas",
    address: "456 Cypress Avenue",
    mobile: "555-9012",
    email: "jack.thomas@example.com",
    department: "Quality Assurance",
    designation: "Inspector",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "4:45PM",
    number: 11
  },
  {
    firstName: "Karen",
    lastName: "Jackson",
    address: "789 Redwood Road",
    mobile: "555-0123",
    email: "karen.jackson@example.com",
    department: "Logistics",
    designation: "Coordinator",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "5:00PM",
    number: 12
  },
  {
    firstName:"John",
    lastName:"Doe",
    address:"123 Elm street",
    mobile:"555-1234",
    email:"John.doe@example.com",
    department:"Sales",
    designation:"Manager",
    updatedIcon:"J",
    updatedDate:"2024-05-08",
    updatedTime:"1:45PM",
    number:1
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    address: "456 Oak Avenue",
    mobile: "555-5678",
    email: "jane.smith@example.com",
    department: "Marketing",
    designation: "Director",
    updatedIcon: "S",
    updatedDate: "2024-03-08",
    updatedTime: "2:10PM",
    number: 2
  },
  {
    firstName: "Alice",
    lastName: "Johnson",
    address: "789 Pine Road",
    mobile: "555-8765",
    email: "alice.johnson@example.com",
    department: "HR",
    designation: "Coordinator",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "2:30PM",
    number: 3
  },
  {
    firstName: "Bob",
    lastName: "Brown",
    address: "321 Maple Lane",
    mobile: "555-2345",
    email: "bob.brown@example.com",
    department: "IT",
    designation: "Technician",
    updatedIcon: "B",
    updatedDate: "2024-03-08",
    updatedTime: "3:00PM",
    number: 4
  },
  {
    firstName: "Charlie",
    lastName: "Davis",
    address: "654 Birch Boulevard",
    mobile: "555-3456",
    email: "charlie.davis@example.com",
    department: "Finance",
    designation: "Analyst",
    updatedIcon: "B",
    updatedDate: "2024-03-08",
    updatedTime: "3:15PM",
    number: 5
  },
  {
    firstName: "Eve",
    lastName: "Miller",
    address: "987 Cedar Street",
    mobile: "555-4567",
    email: "eve.miller@example.com",
    department: "Operations",
    designation: "Supervisor",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "3:30PM",
    number: 6
  },
  {
    firstName: "Frank",
    lastName: "Wilson",
    address: "321 Spruce Way",
    mobile: "555-5678",
    email: "frank.wilson@example.com",
    department: "Legal",
    designation: "Consultant",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "3:45PM",
    number: 7
  },
  {
    firstName: "Grace",
    lastName: "Lee",
    address: "654 Palm Drive",
    mobile: "555-6789",
    email: "grace.lee@example.com",
    department: "Engineering",
    designation: "Developer",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "4:00PM",
    number: 8
  },
  {
    firstName: "Henry",
    lastName: "Taylor",
    address: "987 Fir Street",
    mobile: "555-7890",
    email: "henry.taylor@example.com",
    department: "R&D",
    designation: "Scientist",
    updatedIcon: "A",
    updatedDate: "2024-03-08",
    updatedTime: "4:15PM",
    number: 9
  },
  {
    firstName: "Isabel",
    lastName: "Anderson",
    address: "123 Aspen Court",
    mobile: "555-8901",
    email: "isabel.anderson@example.com",
    department: "Customer Support",
    designation: "Agent",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "4:30PM",
    number: 10
  },
  {
    firstName: "Jack",
    lastName: "Thomas",
    address: "456 Cypress Avenue",
    mobile: "555-9012",
    email: "jack.thomas@example.com",
    department: "Quality Assurance",
    designation: "Inspector",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "4:45PM",
    number: 11
  },
  {
    firstName: "Karen",
    lastName: "Jackson",
    address: "789 Redwood Road",
    mobile: "555-0123",
    email: "karen.jackson@example.com",
    department: "Logistics",
    designation: "Coordinator",
    updatedIcon: "J",
    updatedDate: "2024-03-08",
    updatedTime: "5:00PM",
    number: 12
  }
];